include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "*g.dart"
    - "*.freezed.dart"
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
    - "lib/*.config.dart"
    
  errors:
    missing_return: error
    missing_required_param: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore